backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('home');
});
Auth::routes([
    'register' => true,
    'confirm' => true,
    'verify' => false,
]);

Route::middleware('auth')->group(function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::post('/{wishThing}/purchase', 'PurchaseController')->name('purchase');


    Route::prefix('user')->name('user.')->group(function () {

        Route::get('/edit', 'UserController@edit')->name('edit');
        Route::get('/change-password', 'UserController@changePassword')->name('change_password');
        Route::put('/update', 'UserController@update')->name('update');

    });


    Route::prefix('wish-thing')->name('wish_thing.')->group(function () {

        Route::get('/create/{wishThing}/allow', 'WishThingController@allow')->name('allow');
        Route::get('/create/{wishThing}/disallow', 'WishThingController@disallow')->name('disallow');
        Route::get('/list', 'WishThingController@list')->name('list');
        Route::get('/history', 'WishThingController@history')->name('history');
        Route::put('/{wishThing}/reset-purchase', 'WishThingController@resetPurchase')->name('reset_purchase');


        // Route::resource('/', 'WishThingController');
        // 上の記述で下記のルートが全て作成される
        Route::get('/', 'WishThingController@index')->name('index');
        Route::get('/create', 'WishThingController@create')->name('create');
        Route::post('/', 'WishThingController@store')->name('store');
        // Route::get('/{wishThing}', 'WishThingController@show')->name('show');
        Route::get('/{wishThing}/edit', 'WishThingController@edit')->name('edit');
        Route::put('/{wishThing}', 'WishThingController@update')->name('update');
        Route::delete('/{wishThing}', 'WishThingController@destroy')->name('destroy');

    });
    // 仮実装　本実装時は上記のように
    /*
    Route::get('/budget/edit', function(){
        return view('budget.edit');
    })->name('budget.edit');
    */
    Route::prefix('budget')->name('budget.')->group(function () {
        Route::get('/edit/allow', 'BudgetController@allow')->name('allow');
        Route::get('/edit/disallow', 'BudgetController@disallow')->name('disallow');

        Route::get('/', 'BudgetController@index')->name('index');
        Route::get('/edit', 'BudgetController@edit')->name('edit');
        Route::put('/{budget}', 'BudgetController@update')->name('update');
    });
    
});

backend/app/Models/WishThing.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * Class WishThing
 * 
 * @property int $id
 * @property int $user_id
 * @property string $name
 * @property int $price
 * @property int $priority
 * @property Carbon|null $time_limit
 * @property Carbon|null $purchase_date
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * 
 * @property User $user
 * @property Collection|Budget[] $budgets
 *
 * @package App\Models
 */
class WishThing extends Model
{
	protected $table = 'wish_things';

	protected $casts = [
		'user_id' => 'int',
		'price' => 'int',
		'priority' => 'int'
	];

	protected $dates = [
		'time_limit',
		'purchase_date'
	];

	protected $fillable = [
		'user_id',
		'name',
		'price',
		'priority',
		'time_limit',
		'purchase_date'
	];

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function budgets()
	{
		return $this->hasMany(Budget::class, 'next_with_thing_id');
	}
}

backend/app/Http/Controllers/WishThingController.php
<?php

namespace App\Http\Controllers;

use App\Models\WishThing;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\WishThingRequest;
use App\Services\WishThingService;

class WishThingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     * 欲しいもの追加画面表示
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('wish_thing.add');
    }

    /**
     * 購入許可画面表示
     *
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function allow(WishThing $wishThing)
    {
        return view('wish_thing.allow', compact(
            'wishThing'
        ));
    }

    /**
     * 購入不許可画面表示
     *
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function disallow(WishThing $wishThing, WishThingService $service)
    {
        $this_wish_thing = $wishThing;
        $suggest_wish_thing = $service->suggestWishThing();
        $shortage = $service->calcShortage();

        return view('wish_thing.disallow', compact(
            'this_wish_thing',
            'suggest_wish_thing',
            'shortage',
        ));
    }

    /**
     * 欲しいものリスト画面表示
     *
     * @return \Illuminate\Http\Response
     */
    public function list()
    {
        $wish_list = WishThing::query()
            ->where('user_id', Auth::id())
            ->orderBy('priority', 'desc')
            ->orderBy('price', 'asc')
            ->whereNull('purchase_date')
            ->get();

        return view('wish_thing.list', compact(
            'wish_list',
        ));
    }

    /**
     * 買ったもの履歴画面表示
     *
     * @return \Illuminate\Http\Response
     */
    public function history()
    {
        $purchased_list = WishThing::query()
            ->where('user_id', Auth::id())
            ->orderBy('purchase_date', 'desc')
            ->whereNotNull('purchase_date')
            ->get();

        return view('wish_thing.history', compact(
            'purchased_list',
        ));
    }


    /**
     * Store a newly created resource in storage.
     * 欲しいもの追加機能
     *
     * @param  \App\Http\Requests;WishThingRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WishThingRequest $request, WishThingService $wishThingService)
    {
        $wishThing = new WishThing();
        $wishThing->fill($request->all());
        $wishThing->user_id = Auth::id();
        
        try {

            \DB::transaction(function () use ($wishThing) {
                $wishThing->save();
            });

            $target_root = null; // 遷移先

            if ( empty(Auth::user()->budget) ) {
                // 買い物予算が未設定であればダッシュボードへ遷移
                $target_root = route('dashboard');
        
            } elseif ( $wishThingService->isShouldBuy($wishThing) ) {
                // 登録した欲しいものが一番買うべきものであれば購入許可画面へ遷移
                $target_root = route('wish_thing.allow', $wishThing->id);
                
            } else {
                $target_root = route('wish_thing.disallow', $wishThing->id);
            }

            return redirect($target_root)
                ->with('flash', ['type' => 'success', 'message' => __('messages.wish_thing.add.success')]);

        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return back()
                ->withInput($request->input())
                ->with('flash', ['type' => 'danger', 'message' => __('messages.wish_thing.add.failed')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function show(WishThing $wishThing)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * 欲しいもの編集画面表示
     *
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function edit(WishThing $wishThing)
    {
        return view('wish_thing.edit', compact(
            'wishThing'
        ));
    }

    /**
     * Update the specified resource in storage.
     * 欲しいもの更新処理
     * 
     * @param  \App\Http\Requests\WishThingRequest  $request
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function update(WishThingRequest $request, WishThing $wishThing)
    {
        $wishThing->fill($request->all());
        
        try {

            \DB::transaction(function () use ($wishThing) {
                $wishThing->save();
            });

            return redirect(route('wish_thing.list'))
                ->with('flash', ['type' => 'success', 'message' => __('messages.wish_thing.edit.success')]);

        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return back()
                ->withInput($request->input())
                ->with('flash', ['type' => 'danger', 'message' => __('messages.wish_thing.edit.failed')]);
        }

    }

    /**
     * Remove the specified resource from storage.
     * 欲しいもの削除処理
     *
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function destroy(WishThing $wishThing)
    {        
        try {

            \DB::transaction(function () use ($wishThing) {
                $wishThing->delete();
            });

            return redirect(route('wish_thing.list'))
                ->with('flash', ['type' => 'success', 'message' => __('messages.wish_thing.delete.success')]);

        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return back()
                ->with('flash', ['type' => 'danger', 'message' => __('messages.wish_thing.delete.failed')]);
        }

    }

    /**
     * Update the specified resource in storage.
     * 買ったもの取消処理
     *
     * @param  \App\Models\WishThing  $wishThing
     * @return \Illuminate\Http\Response
     */
    public function resetPurchase(WishThing $wishThing)
    {
        
        try {

            $wishThing->purchase_date = null;

            \DB::transaction(function () use ($wishThing) {
                $wishThing->save();
            });

            return redirect(route('wish_thing.history'))
                ->with('flash', ['type' => 'success', 'message' => __('messages.wish_thing.reset_purchase.success')]);

        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return back()
                ->with('flash', ['type' => 'danger', 'message' => __('messages.wish_thing.reset_purchase.failed')]);
        }

    }


}

backend/resources/views/wish_thing/add.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">欲しいもの追加</h1>
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="{{ route('wish_thing.store') }}" class="user">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="form-group">
                                <label for="name">
                                    <h3>欲しいもの</h3>
                                </label>
                                <input type="text"
                                    class="mb-4 form-control form-control-user @error('name') is-invalid @enderror"
                                    id="name" name="name" value="{{ old('name') }}">
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="mt-2" for="cost">値段</label>
                                <input type="number"
                                    class="mb-2 form-control form-control-user @error('price') is-invalid @enderror"
                                    id="price" name="price" value="{{ old('price') }}">
                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="priority">欲しい度</label>
                                <input type="range"
                                    class="mb-2 form-control-range form-control-user @error('priority') is-invalid @enderror"
                                    id="priority" name="priority" value="{{ old('priority') }}">
                                @error('priority')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="time_limit">期限</label>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input" checked>
                                    <label class="custom-control-label" for="customRadio1">なし</label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                                    <label class="custom-control-label" for="customRadio2">あり</label>
                                </div>
                                {{-- TODO:期限ありの場合に期限フォームを表示 --}}
                                <input type="radio"
                                    class="mb-4 custom-control-input form-control-user @error('time_limit') is-invalid @enderror"
                                    id="time_limit" name="time_limit" value="{{ old('time_limit') }}">
                                @error('time_limit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <button type="submit" class="mt-4 btn btn-primary btn-user btn-block">
                                {{ __('追加する') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

backend/resources/views/wish_thing/allow.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="#" class="user">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="text-center">
                                <h6>そんなに欲しいなら仕方がない</h6>
                                <h2 class="font-weight-bold">
                                    {{ $wishThing->name }}は<br>買ってよし！
                                </h2>
                            </div>
                            

                            <button type="button" class="btn btn-primary btn-user btn-block"
                                data-toggle="modal" data-target="#purchaseModal">
                                {{ __('購入する') }}
                            </button>
                            <a href="{{ route('dashboard') }}" class="btn btn-outline-secondary btn-user btn-block">
                                {{ __('ダッシュボードへ戻る') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <form id="purchase-form" action="{{ route('purchase', $wishThing->id) }}" method="POST" style="display: none;">
        @csrf
    </form>
@endsection

backend/resources/views/wish_thing/disallow.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="GET" action="{{ route('budget.edit') }}" class="user">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div>
                                <h2 class="text-center font-weight-bold text-nowrap">
                                    {{ $this_wish_thing->name }}より先に<br>
                                    {{ $suggest_wish_thing->name }}を買いましょう
                                </h2>
                                @if ($shortage > 0)
                                <h6 class="text-right">
                                    {{ $suggest_wish_thing->name }}が買えるようになるまで<br>
                                    あと{{ $shortage }}円
                                </h6>
                                @endif
                            </div>
                            

                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                {{ __('買い物予算を更新する') }}
                            </button>
                            <a href="{{ route('dashboard') }}" class="btn btn-outline-secondary btn-user btn-block">
                                {{ __('ダッシュボードへ戻る') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

backend/resources/views/wish_thing/edit.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">欲しいもの編集</h1>
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="{{ route('wish_thing.update', $wishThing->id) }}" class="user">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="form-group">
                                <label for="name">
                                    <h3>欲しいもの</h3>
                                </label>
                                <input type="text"
                                    class="mb-4 form-control form-control-user @error('name') is-invalid @enderror"
                                    id="name" name="name" value="{{ old('name', $wishThing->name) }}">
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="mt-2" for="price">値段</label>
                                <input type="number"
                                    class="mb-2 form-control form-control-user @error('price') is-invalid @enderror"
                                    id="price" name="price" value="{{ old('price', $wishThing->price) }}">
                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="priority">欲しい度</label>
                                <input type="range"
                                    class="mb-2 form-control-range form-control-user @error('priority') is-invalid @enderror"
                                    id="priority" name="priority" value="{{ old('priority', $wishThing->priority) }}">
                                @error('priority')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="time_limit">期限</label>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input" checked>
                                    <label class="custom-control-label" for="customRadio1">なし</label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                                    <label class="custom-control-label" for="customRadio2">あり</label>
                                </div>
                                {{-- TODO:期限ありの場合に期限フォームを表示 --}}
                                <input type="radio"
                                    class="mb-4 custom-control-input form-control-user @error('time_limit') is-invalid @enderror"
                                    id="time_limit" name="time_limit" value="{{ old('time_limit', $wishThing->time_limit) }}">
                                @error('time_limit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <button type="submit" class="mt-4 btn btn-primary btn-user btn-block">
                                {{ __('更新する') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

backend/resources/views/wish_thing/history.blade.php
@extends('layouts.app')

@section('content')
    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">買ったもの履歴</h1>
    </div>

    {{-- Content Row --}}
    <div class="row">
        {{-- Area Chart --}}
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                {{-- Card Header - Dropdown --}}
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">買ったもの履歴</h6>
                </div>
                {{-- Card Body --}}
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{-- 買ったものリスト --}}
                    <table class="table">
                        <thead>
                            <tr>
                              <th>購入日</th>
                              <th>商品名</th>
                              <th>値段</th>
                              <th></th>
                            </tr>
                          </thead>
                        @foreach ($purchased_list as $index => $wishThing)
                        
                          <tbody>
                            <tr>
                                <th scope="row">{{ $wishThing->purchase_date->format('Y/m/d') }}</th>
                                <td>{{ $wishThing->name }}</td>
                                <td>{{ $wishThing->price }}円</td>
                                <td>
                                    <a class="nav-link" href="#" data-toggle="modal" data-target="#resetPurchaseModal">
                                        <i class="fas fa-reply" data-toggle="tooltip" data-placement="top" title="欲しいものリストに戻す"></i>
                                    </a>
                                    <form id="reset-purchase-form" action="{{ route('wish_thing.reset_purchase', $wishThing->id) }}" method="POST" style="display: none;">
                                        <input type="hidden" name="_method" value="PUT">
                                        @csrf
                                    </form>
                                </td>
                            </tr>
                          </tbody>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

backend/resources/views/wish_thing/list.blade.php
@extends('layouts.app')

@section('content')
    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">欲しいものリスト</h1>
    </div>

    {{-- Content Row --}}
    <div class="row">
        {{-- Area Chart --}}
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                {{-- Card Header - Dropdown --}}
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">欲しいものリスト</h6>
                </div>
                {{-- Card Body --}}
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{-- 欲しいものリスト --}}
                    <table class="table">
                        @foreach ($wish_list as $index => $wishThing)
                        <tr>
                            <th scope="row">{{ $index + 1 }}</th>
                            <td>{{ $wishThing->name }}</td>
                            <td>{{ $wishThing->price }}円</td>
                            <td>
                                <a class="nav-link" href="{{ route('wish_thing.edit', $wishThing->id) }}">
                                    <i class="fas fa-edit" data-toggle="tooltip" data-placement="top" title="編集する"></i>
                                </a>
                            </td>
                            <td>
                                <a class="nav-link" href="#" data-toggle="modal" data-target="#deleteWishThingModal">
                                    <i class="fas fa-trash-alt" data-toggle="tooltip" data-placement="top" title="削除する"></i>
                                </a>
                                <form id="delete-wish-thing-form" action="{{ route('wish_thing.destroy', $wishThing->id) }}" method="POST" style="display: none;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    @csrf
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection