backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('home');
});
Auth::routes([
    'register' => true,
    'confirm' => true,
    'verify' => false,
]);

Route::middleware('auth')->group(function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::post('/{wishThing}/purchase', 'PurchaseController')->name('purchase');


    Route::prefix('user')->name('user.')->group(function () {

        Route::get('/edit', 'UserController@edit')->name('edit');
        Route::get('/change-password', 'UserController@changePassword')->name('change_password');
        Route::put('/update', 'UserController@update')->name('update');

    });


    Route::prefix('wish-thing')->name('wish_thing.')->group(function () {

        Route::get('/create/{wishThing}/allow', 'WishThingController@allow')->name('allow');
        Route::get('/create/{wishThing}/disallow', 'WishThingController@disallow')->name('disallow');
        Route::get('/list', 'WishThingController@list')->name('list');
        Route::get('/history', 'WishThingController@history')->name('history');
        Route::put('/{wishThing}/reset-purchase', 'WishThingController@resetPurchase')->name('reset_purchase');


        // Route::resource('/', 'WishThingController');
        // 上の記述で下記のルートが全て作成される
        Route::get('/', 'WishThingController@index')->name('index');
        Route::get('/create', 'WishThingController@create')->name('create');
        Route::post('/', 'WishThingController@store')->name('store');
        // Route::get('/{wishThing}', 'WishThingController@show')->name('show');
        Route::get('/{wishThing}/edit', 'WishThingController@edit')->name('edit');
        Route::put('/{wishThing}', 'WishThingController@update')->name('update');
        Route::delete('/{wishThing}', 'WishThingController@destroy')->name('destroy');

    });
    // 仮実装　本実装時は上記のように
    /*
    Route::get('/budget/edit', function(){
        return view('budget.edit');
    })->name('budget.edit');
    */
    Route::prefix('budget')->name('budget.')->group(function () {
        Route::get('/edit/allow', 'BudgetController@allow')->name('allow');
        Route::get('/edit/disallow', 'BudgetController@disallow')->name('disallow');

        Route::get('/', 'BudgetController@index')->name('index');
        Route::get('/edit', 'BudgetController@edit')->name('edit');
        Route::put('/{budget}', 'BudgetController@update')->name('update');
    });
    
});

backend/app/Models/Budget.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Budget
 * 
 * @property int $id
 * @property int $user_id
 * @property int $amount
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * 
 * @property WishThing $wish_thing
 * @property User $user
 *
 * @package App\Models
 */
class Budget extends Model
{
	protected $table = 'budgets';

	protected $casts = [
		'user_id' => 'int',
		'amount' => 'int'
	];

	protected $fillable = [
		'user_id',
		'amount'
	];

	public function user()
	{
		return $this->belongsTo(User::class);
	}
}

backend/app/Http/Controllers/BudgetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Budget;
use Illuminate\Http\Request;
use App\Http\Requests\BudgetRequest;
use Illuminate\Support\Facades\Auth;
use App\Services\WishThingService;

class BudgetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        
        $budget = Budget::query()
            ->where('user_id', Auth::id())
            ->first();
        
        return view('budget.edit', compact(
            'budget'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BudgetRequest $request, WishThingService $wishThingService, Budget $budget)
    {
        $budget->amount = $request->amount;
        
        try {

            \DB::transaction(function () use ($budget) {
                $budget->save();
            });
            //$suggest_wish_thing = $service->suggestWishThing();

            $target_root = null; // 遷移先

            if ( $wishThingService->calcShortage() >= 0 ) {
                // 予算が欲しいものの価格以上であれば購入許可画面へ遷移
                $target_root = route('budget.allow');
                
            } else {
                $target_root = route('budget.disallow');
            }

            return redirect($target_root)
                ->with('flash', ['type' => 'success', 'message' => __('messages.budget.edit.success')]);

        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return back()
                ->withInput($request->input())
                ->with('flash', ['type' => 'danger', 'message' => __('messages.budget.edit.failed')]);
        }
    }

    /**
     * 購入許可画面表示
     */
    public function allow(WishThingService $service)
    {
        $wishThing = $service->suggestWishThing();
        return view('budget.allow', compact(
            'wishThing'
        ));
    }
    /**
     * 購入不許可画面表示
     */
    public function disallow(WishThingService $service)
    {
        $suggest_wish_thing = $service->suggestWishThing();
        $shortage = -($service->calcShortage());

        return view('budget.disallow', compact(
            'suggest_wish_thing',
            'shortage'
        ));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

backend/resources/views/budget/allow.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="#" class="user">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="text-center">
                                <h6>衝動を抑えてよくお金を貯めました</h6>
                                <h2 class="font-weight-bold">
                                    {{ $wishThing->name }}は<br>買ってよし！
                                </h2>
                            </div>
                            

                            <button type="button" class="btn btn-primary btn-user btn-block"
                                data-toggle="modal" data-target="#purchaseModal">
                                {{ __('購入する') }}
                            </button>
                            <a href="{{ route('dashboard') }}" class="btn btn-outline-secondary btn-user btn-block">
                                {{ __('ダッシュボードへ戻る') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <form id="purchase-form" action="{{ route('purchase', $wishThing->id) }}" method="POST" style="display: none;">
        @csrf
    </form>
@endsection

backend/resources/views/budget/disallow.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                @csrf

                {{-- Card Header --}}
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>


                {{-- Card Body --}}
                <div class="card-body">
                    <div class="container">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <div>
                            <h2 class="text-center font-weight-bold text-nowrap">
                                貯金してえらい
                            </h2>
                            @if ($shortage > 0)
                            <h6 class="text-center text-nowrap">
                                {{ $suggest_wish_thing->name }}が買えるようになるまで<br>
                                あと{{ $shortage }}円
                            </h6>
                            @endif
                        </div>
                        
                        <a href="{{ route('dashboard') }}" class="btn btn-outline-secondary btn-user btn-block">
                            {{ __('ダッシュボードへ戻る') }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

backend/resources/views/budget/edit.blade.php
@extends('layouts.app')

@section('content')
    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">買い物予算更新</h1>
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="{{ route('budget.update', $budget->id) }}" class="user">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <div class="form-group">
                                <label class="mt-2" for="amount">
                                    <h3>現在の買い物予算</h3>
                                </label>
                                <input type="number"
                                    class="mb-2 form-control form-control-user"
                                    id="amount_old" name="amount_old" value="{{ $budget->amount }}" readonly>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="mt-2" for="amount">
                                    <h3>新しい買い物予算</h3>
                                </label>
                                <input type="number"
                                    class="mb-2 form-control form-control-user @error('amount') is-invalid @enderror"
                                    id="amount" name="amount" value="">
                                @error('amount')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <button type="submit" class="mt-4 btn btn-primary btn-user btn-block">
                                {{ __('更新する') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection