backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('home');
});
Auth::routes([
    'register' => true,
    'confirm' => true,
    'verify' => false,
]);

Route::middleware('auth')->group(function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::post('/{wishThing}/purchase', 'PurchaseController')->name('purchase');


    Route::prefix('user')->name('user.')->group(function () {

        Route::get('/edit', 'UserController@edit')->name('edit');
        Route::get('/change-password', 'UserController@changePassword')->name('change_password');
        Route::put('/update', 'UserController@update')->name('update');

    });


    Route::prefix('wish-thing')->name('wish_thing.')->group(function () {

        Route::get('/create/{wishThing}/allow', 'WishThingController@allow')->name('allow');
        Route::get('/create/{wishThing}/disallow', 'WishThingController@disallow')->name('disallow');
        Route::get('/list', 'WishThingController@list')->name('list');
        Route::get('/history', 'WishThingController@history')->name('history');
        Route::put('/{wishThing}/reset-purchase', 'WishThingController@resetPurchase')->name('reset_purchase');


        // Route::resource('/', 'WishThingController');
        // 上の記述で下記のルートが全て作成される
        Route::get('/', 'WishThingController@index')->name('index');
        Route::get('/create', 'WishThingController@create')->name('create');
        Route::post('/', 'WishThingController@store')->name('store');
        // Route::get('/{wishThing}', 'WishThingController@show')->name('show');
        Route::get('/{wishThing}/edit', 'WishThingController@edit')->name('edit');
        Route::put('/{wishThing}', 'WishThingController@update')->name('update');
        Route::delete('/{wishThing}', 'WishThingController@destroy')->name('destroy');

    });
    // 仮実装　本実装時は上記のように
    /*
    Route::get('/budget/edit', function(){
        return view('budget.edit');
    })->name('budget.edit');
    */
    Route::prefix('budget')->name('budget.')->group(function () {
        Route::get('/edit/allow', 'BudgetController@allow')->name('allow');
        Route::get('/edit/disallow', 'BudgetController@disallow')->name('disallow');

        Route::get('/', 'BudgetController@index')->name('index');
        Route::get('/edit', 'BudgetController@edit')->name('edit');
        Route::put('/{budget}', 'BudgetController@update')->name('update');
    });
    
});

backend/app/Models/User.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;



/**
 * Class User
 * 
 * @property int $id
 * @property string $name
 * @property string $email
 * @property Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * 
 * @property Budget $budget
 * @property Collection|WishThing[] $wish_things
 *
 * @package App\Models
 */
class User extends Authenticatable
{

	use Notifiable;


	protected $table = 'users';

	protected $dates = [
		'email_verified_at'
	];

	protected $hidden = [
		'password',
		'remember_token'
	];

	protected $fillable = [
		'name',
		'email',
		'email_verified_at',
		'password',
		'remember_token'
	];

	public function budget()
	{
		return $this->hasOne(Budget::class);
	}

	public function wish_things()
	{
		return $this->hasMany(WishThing::class);
	}
}

backend/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Show the form for editing the specified resource.
     * プロフィール変更画面表示
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        $user = Auth::user();

        return view('user.edit', compact(
            'user'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     * パスワード変更画面表示
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function changePassword()
    {
        $user = Auth::user();

        return view('user.change_password', compact(
            'user'
        ));
    }

    /**
     * Update the specified resource in storage.
     * ユーザー情報更新処理
     * 
     * @param  \App\Http\Requests\UserRequest $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request)
    {
                
        $user = Auth::user();
        $user->fill($request->all());
        $user->password = bcrypt($request->get('password')) ?? null;
        
        try {

            \DB::transaction(function () use ($user) {
                $user->save();
            });

            return redirect(route('dashboard'))
                ->with('flash', ['type' => 'success', 'message' => __('messages.user.edit.success')]);

        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return back()
                ->withInput($request->input())
                ->with('flash', ['type' => 'danger', 'message' => __('messages.user.edit.failed')]);
        }

    }

}

backend/resources/views/user/change_password.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">パスワード変更</h1>
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="{{ route('user.update') }}" class="user">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="form-group">
                                <label class="mt-2" for="old-password">現在のパスワード</label>
                                <input type="password"
                                    class="mb-2 form-control form-control-user @error('old_password') is-invalid @enderror"
                                    id="old-password" name="old_password" value="{{ old('old_password') }}">
                                @error('old_password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="mt-2" for="password">新しいパスワード</label>
                                <input type="password"
                                    class="mb-2 form-control form-control-user @error('password') is-invalid @enderror"
                                    id="password" name="password" value="{{ old('password') }}">
                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="mt-2" for="password-confirmation">新しいパスワード（確認）</label>
                                <input type="password"
                                    class="mb-2 form-control form-control-user @error('password_confirmation') is-invalid @enderror"
                                    id="password-confirmation" name="password_confirmation" value="{{ old('password_confirmation') }}">
                                @error('password_confirmation')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <button type="submit" class="mt-4 btn btn-primary btn-user btn-block">
                                {{ __('パスワードを変更する') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

backend/resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')

    {{-- Page Heading --}}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">プロフィール変更</h1>
    </div>

    <div class="row justify-content-center">
        {{-- Area Chart --}}
        <div class="col-xl-8 col-lg-12">

            <div class="card shadow mb-4">
                <form method="POST" action="{{ route('user.update') }}" class="user">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf

                    {{-- Card Header --}}
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>


                    {{-- Card Body --}}
                    <div class="card-body">
                        <div class="container">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            <div class="form-group">
                                <label class="mt-2" for="name">ユーザー名</label>
                                <input type="text"
                                    class="mb-2 form-control form-control-user @error('name') is-invalid @enderror"
                                    id="name" name="name" value="{{ old('name', $user->name) }}">
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="mt-2" for="email">メールアドレス</label>
                                <input type="email"
                                    class="mb-2 form-control form-control-user @error('email') is-invalid @enderror"
                                    id="email" name="email" value="{{ old('email', $user->email) }}">
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <hr>
                            <button type="submit" class="mt-4 btn btn-primary btn-user btn-block">
                                {{ __('更新する') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection