backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('home');
});
Auth::routes([
    'register' => true,
    'confirm' => true,
    'verify' => false,
]);

Route::middleware('auth')->group(function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::post('/{wishThing}/purchase', 'PurchaseController')->name('purchase');


    Route::prefix('user')->name('user.')->group(function () {

        Route::get('/edit', 'UserController@edit')->name('edit');
        Route::get('/change-password', 'UserController@changePassword')->name('change_password');
        Route::put('/update', 'UserController@update')->name('update');

    });


    Route::prefix('wish-thing')->name('wish_thing.')->group(function () {

        Route::get('/create/{wishThing}/allow', 'WishThingController@allow')->name('allow');
        Route::get('/create/{wishThing}/disallow', 'WishThingController@disallow')->name('disallow');
        Route::get('/list', 'WishThingController@list')->name('list');
        Route::get('/history', 'WishThingController@history')->name('history');
        Route::put('/{wishThing}/reset-purchase', 'WishThingController@resetPurchase')->name('reset_purchase');


        // Route::resource('/', 'WishThingController');
        // 上の記述で下記のルートが全て作成される
        Route::get('/', 'WishThingController@index')->name('index');
        Route::get('/create', 'WishThingController@create')->name('create');
        Route::post('/', 'WishThingController@store')->name('store');
        // Route::get('/{wishThing}', 'WishThingController@show')->name('show');
        Route::get('/{wishThing}/edit', 'WishThingController@edit')->name('edit');
        Route::put('/{wishThing}', 'WishThingController@update')->name('update');
        Route::delete('/{wishThing}', 'WishThingController@destroy')->name('destroy');

    });
    // 仮実装　本実装時は上記のように
    /*
    Route::get('/budget/edit', function(){
        return view('budget.edit');
    })->name('budget.edit');
    */
    Route::prefix('budget')->name('budget.')->group(function () {
        Route::get('/edit/allow', 'BudgetController@allow')->name('allow');
        Route::get('/edit/disallow', 'BudgetController@disallow')->name('disallow');

        Route::get('/', 'BudgetController@index')->name('index');
        Route::get('/edit', 'BudgetController@edit')->name('edit');
        Route::put('/{budget}', 'BudgetController@update')->name('update');
    });
    
});

backend/resources/views/elements/footer.blade.php
{{-- Footer --}}
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Literal 2021</span>
        </div>
    </div>
</footer>
{{-- End of Footer --}}

backend/resources/views/elements/scroll_to_top_button.blade.php
{{-- Scroll to Top Button --}}
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

backend/resources/views/elements/sidebar.blade.php
{{-- Sidebar --}}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    {{-- Sidebar - Brand --}}
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fab fa-creative-commons-nc-jp"></i>
        </div>
        <div class="sidebar-brand-text mx-3 text-nowrap">衝動買わないリスト</div>
    </a>

    {{-- Divider --}}
    <hr class="sidebar-divider my-0">

    {{-- Nav Item - Dashboard --}}
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>ダッシュボード</span></a>
    </li>

    {{-- Divider --}}
    <hr class="sidebar-divider">

    {{-- Heading --}}
    <div class="sidebar-heading">
        Page Menu
    </div>

    {{-- Nav Item - Pages Collapse Menu --}}
    <li class="nav-item">
        <a class="nav-link" href="{{ route('wish_thing.create') }}">
            <i class="fas fa-plus-circle"></i>
            <span>欲しいもの追加</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('wish_thing.list') }}">
            <i class="fas fa-edit"></i>
            <span>欲しいもの編集・削除</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('budget.edit') }}">
            <i class="fas fa-calculator"></i>
            <span>買い物予算変更</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('wish_thing.history') }}">
            <i class="fas fa-history"></i>
            <span>買った物履歴</span>
        </a>
    </li>

    {{-- Nav Item - Utilities Collapse Menu --}}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>ユーザー管理</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('user.edit') }}">プロフィール変更</a>
                <a class="collapse-item" href="{{ route('user.change_password') }}">パスワード変更</a>
                <a class="collapse-item" href="#" data-toggle="modal" data-target="#logoutModal">ログアウト</a>
            </div>
        </div>
    </li>

    {{-- Divider --}}
    <hr class="sidebar-divider">

    {{-- Sidebar Toggler (Sidebar) --}}
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
{{-- End of Sidebar --}}

backend/resources/views/elements/topbar.blade.php
{{-- Topbar --}}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    {{-- Sidebar Toggle (Topbar) --}}
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>


    {{-- Topbar Navbar --}}
    <ul class="navbar-nav ml-auto">

        <div class="topbar-divider d-none d-sm-block">

        </div>

        {{-- Nav Item - User Information --}}
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                <img class="img-profile rounded-circle" src="{{ asset('img/undraw_profile.svg') }}">
            </a>
            {{-- Dropdown - User Information --}}
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route('user.edit') }}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    プロフィール変更
                </a>
                <a class="dropdown-item" href="{{ route('user.change_password') }}">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    パスワード変更
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    ログアウト
                </a>
            </div>
        </li>

    </ul>

</nav>
{{-- End of Topbar --}}